In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split

X_full = pd.read_csv('../../dataset/train.csv', index_col='Id')
X_test_full = pd.read_csv('../../dataset/test.csv', index_col='Id')

# obtain target and predictor
y = X_full.SalePrice
# features = ['LotArea','YearBuilt', '1stFlrSF', '2ndFlrSF',
#             'OverallQual','OverallCond', 'GrLivArea',
#             'FullBath','BedroomAbvGr','TotRmsAbvGrd',
#             'Fireplaces','WoodDeckSF','YrSold']
features = ['LotArea', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 
            'FullBath', 'BedroomAbvGr', 'TotRmsAbvGrd']
X = X_full[features].copy()
X_test = X_test_full[features].copy()

X_train, X_val, y_train, y_val = train_test_split(X, y, 
                                                  train_size=0.8,
                                                  test_size=0.2,
                                                  random_state=0)

In [ ]:
X.head()

In [8]:
from sklearn.ensemble import RandomForestRegressor

model_1 = RandomForestRegressor(n_estimators=50, random_state=0)
model_2 = RandomForestRegressor(n_estimators=100, random_state=0)
model_3 = RandomForestRegressor(n_estimators=200, min_samples_split=20, random_state=0)
model_4 = RandomForestRegressor(n_estimators=100, max_depth=7, random_state=0)
# model_5 = RandomForestRegressor(n_estimators=100, criterion='absolute_error', random_state=0)

models = [model_1, model_2, model_3, model_4]#, model_5]

In [9]:
from sklearn.metrics import mean_absolute_error

def score_model(model, X_t=X_train, X_v=X_val, y_t=y_train, y_v=y_val):
    model.fit(X_t, y_t)
    preds = model.predict(X_v)
    return mean_absolute_error(y_v, preds)

for i in range(0, len(models)):
    mae = score_model(models[i])
    print("Model %d MAE: %d" % (i+1, mae))

Model 1 MAE: 24015
Model 2 MAE: 23740
Model 3 MAE: 23996
Model 4 MAE: 23706

In [10]:
best_model = model_4
fin_model = best_model.fit(X_train, y_train)
fin_model.fit(X, y)

preds_test = fin_model.predict(X_val)

output = pd.DataFrame({'Id': X_val.index,
                       'SalePrice': preds_test})
output.to_csv('../../dataset/submission_intermediate.csv', index=False)

In [17]:
subs = pd.read_csv('../../dataset/submission_intermediate.csv', nrows=20)
subs.sort_values(by=['SalePrice'], ascending=False)

      Id      SalePrice
8   1183  699552.295714
6   1404  234965.949823
0    530  232673.193126
16  1323  229424.476797
12  1301  228940.844053
10  1318  191649.541953
3    280  182656.844816
9    688  171524.140269
11  1004  154361.763085
18    32  144373.058642
17    90  143817.265973
1    492  141905.104151
15   255  141551.650243
19   483  139781.150753
7    602  126925.861857
14  1015  124548.879387
13  1393  124347.861993
2    460  115406.131689
5   1014  105869.495052
4    656   99689.421480